### ISSUE TITLE
Consider dropping PHP-5.x

### ISSUE THREAD

**Issue by peter279k** [adriengibrat/Simple-Database-PHP-Class#11]
Since the `php-7.0` version has been released in `2016`.

I think it's time to upgrade this `PHP` version to `7.x` now.

**Comment by adriengibrat** [comment]
I'm not maintaining this repo since 4 years, I didn't wrote PHP since 5 years, so I'm not even sure about what does a migration to PHP 7 would look like ;).

https://github.com/adriengibrat/Simple-Database-PHP-Class/blob/master/Db.php#L4 just imply the minimal PHP version required.
