### ISSUE TITLE
 Uncaught exception 'PDOException' when using pgsql

### ISSUE THREAD

**Issue by daryllukas** [adriengibrat/Simple-Database-PHP-Class#9]
I'm getting the following error when using postgresql driver. Note that I renamed the class to ```db-utility.php```.

```
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "UTF8" at character 11' in /home/daryl/db-utility.php:111
Stack trace:
#0 /home/daryl/db-utility.php(111): PDO->exec('SET NAMES UTF8')
#1 /home/daryl/db-utility-test.php(5): Db->__construct('pgsql', 'localhost', test', 'test')
#2 {main}
  thrown in /home/daryl/db-utility.php on line 111
```

My code in ```db-utility-test.php``` is:
```
require_once('db-utility.php');

$pg = new Db('pgsql', 'localhost', 'test', 'test');

$rs = $pg->read('users', 1);

if(!$rs) {
	die('FailBilling');
} else {
	die('Success');
}
```

**Comment by adriengibrat** [comment]
Hello,

It seems my [last commit](https://github.com/adriengibrat/Simple-Database-PHP-Class/commit/6f6a857346b1e51824b55b35f795ff97ea95ba34) contains SQL command that postgres doesn't like ;)

I don't have a postgres server to test, but i think quoting the UTF8 keyword shoud be the solution.
I've made a [quick fix](https://github.com/adriengibrat/Simple-Database-PHP-Class/commit/6e2c9e05fd0117537e20d070eb0eaa6dac24c0ed), could you tell me if this works?

If not, just comment the line so you're not stuck, and i'll investigate about this bug.

**Comment by adriengibrat** [comment]
no news, good news ...
